apiVersion: v1
kind: Service
metadata:
  name: video-service-web
  labels:
    app: video-service-web
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
  selector:
    app: video-service-web

